<?php

namespace SHARINE\CategorieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{

    public function getAllCategories(){
        $query = $this->getEntityManager()
            ->createQuery("SELECT e FROM SHARINECategorieBundle:Categorie e");
        return $query->getArrayResult();
    }

}
