<?php

namespace SHARINE\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUserById($id){
        return $this->_em->createQueryBuilder()
            ->select('a')
            ->from('SHARINEUserBundle:User' , 'a')
            ->Where('a.id = :id')
            ->setParameter( 'id', $id )
            ->getQuery()
            ->getArrayResult();
    }

    public function getNomEmail(){
        return $this->_em->createQueryBuilder()
            ->select('a.id,a.username,a.email,a.is_archive')
            ->from('SHARINEUserBundle:User' , 'a')
            ->orderBy('a.is_archive,a.username')
            ->getQuery()
            ->getResult();
    }

}
