<?php

namespace SHARINE\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends EntityRepository
{

    public function getCommentairesByArticle($idArticle){
        return $this->_em->createQueryBuilder()
            ->select('u.username,c.date,c.message,a.titre,c.titre,c.id')
            ->from('SHARINEArticleBundle:Commentaire' , 'c')
            ->join('c.article', 'a')
            ->join('c.user', 'u')
            ->Where('a.id = :id')
            ->andWhere('c.user = u.id')
            ->orderBy('c.date', 'DESC')
            ->setParameter( 'id', $idArticle )
            ->getQuery()
            ->getResult();
    }
}
