<?php

namespace SHARINE\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    public function deleteImg($id){
        $qb = $this->_em->createQueryBuilder();
        $q = $qb->delete('SHARINEArticleBundle:Image', 'a')
            ->where('a.id = :id')
            ->setParameter('id', $id)
            ->getQuery();
        $p = $q->execute();
    }
}
