sharine_article_homepage:
    path:     /hello/{name}
    defaults: { _controller: SHARINEArticleBundle:Default:index }

nouvelle_publication:
    path:     /nouvelle_publication
    defaults: { _controller: SHARINEArticleBundle:Article:nouveau }

mes_publication:
    path:     /mes_publication
    defaults: { _controller: SHARINEArticleBundle:Article:mesPublication }

administration:
    path:     /administration/{categorie}
    defaults: { _controller: SHARINEUserBundle:Default:administration, categorie:null }

publication:
    path:     /publication/{id}
    defaults: { _controller: SHARINEArticleBundle:Article:publication, id:null }

publicationAdmin:
    path:     /publicationAdmin/{id}
    defaults: { _controller: SHARINEArticleBundle:Article:publicationAdmin, id:null }

validerPublication:
    path:     /validerPublication/{id}
    defaults: { _controller: SHARINEArticleBundle:Article:validerPublication, id:null }

refuserPublication:
    path:     /refuserPublication
    defaults: { _controller: SHARINEArticleBundle:Article:refuserPublication}

utilisateurGestion:
    path:     /utilisateurGestion
    defaults: {_controller: SHARINEUserBundle:Utilisateur:utilisateurGestion}